"""changed verification token to nullable

Revision ID: b4ad306016be
Revises: f3d276e4aefd
Create Date: 2026-09-01 13:15:04.497628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4ad306016be'
down_revision: Union[str, Sequence[str], None] = 'f3d276e4aefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'verification_token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'verification_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
