"""added order_id to payments

Revision ID: de439a80bc63
Revises: ff07910dd36b
Create Date: 2026-09-10 16:33:58.775232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de439a80bc63'
down_revision: Union[str, Sequence[str], None] = 'ff07910dd36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'order_id')
    # ### end Alembic commands ###
