"""added price constraint to listing

Revision ID: f4da6ef3debd
Revises: 8ec80f87d72d
Create Date: 2026-09-05 12:02:12.951967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4da6ef3debd'
down_revision: Union[str, Sequence[str], None] = '8ec80f87d72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('price_range', 'listings', 'price >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_range', 'listings', type_='check')
    # ### end Alembic commands ###
