"""changed column names to reflect schema names

Revision ID: f5d2e945028f
Revises: f4da6ef3debd
Create Date: 2026-09-07 12:40:55.266089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d2e945028f'
down_revision: Union[str, Sequence[str], None] = 'f4da6ef3debd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_listings",
        "type",
        new_column_name="game_type",
    )
    op.alter_column(
        "skin_listings",
        "name",
        new_column_name="skin_name",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_listings",
        "game_type",
        new_column_name="type",
    )
    op.alter_column(
        "skin_listings",
        "skin_name",
        new_column_name="name",
    )
    # ### end Alembic commands ###
