"""added payments table

Revision ID: ff07910dd36b
Revises: f5d2e945028f
Create Date: 2026-09-08 20:09:22.250328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff07910dd36b'
down_revision: Union[str, Sequence[str], None] = 'f5d2e945028f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'DEPOSIT', 'REFUND', name='payment_type'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='amount_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('balance', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.create_check_constraint('balance_range', 'users', 'balance >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_range', 'users', type_='check')
    op.drop_column('users', 'balance')
    op.drop_table('payments')
    # ### end Alembic commands ###
